# Web properties Spring Boot
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html 

#banner.charset=UTF-8 # Banner file encoding.
banner:
    location: classpath:myBanner.txt
    
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/tfm
        username: TFM
        password: Empstec-93
    jpa:
        show-sql: true
        hibernate: 
            ddl-auto: update
            naming:
                strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect